development: &default
  client_key: "3MVG9xOCXq4ID1uH4x31wtsPMfSKiIXcfKO4fVcPcGAnxoXSuMgrTWS_7QM49IVil_.w5gS.1ATZzgaHF20T."
  client_secret: "130550210458731908"

test:
  <<: *default

production:
  client_key: "3MVG9xOCXq4ID1uH4x31wtsPMfRGqOQFvzMCjQq5BvFRyeNoxmJOLCDpFCxLTldpfHxqy5csWk9fYZTKiwzBs"
  client_secret: "2868984837442939238"
